#!/bin/sh

#este script esta diseñado para llevar a cabo la ejecución de backup del F5, esto aplica para versiones 12, 13 y 14 no he probado en versiones
#anteriores a estas  

TIMESTAMP=`date +%Y%m%d`  #definimos esta variable para que tome la fecha del dia corriente
REMOTE_PATH="/var/local/ucs"   #Esta es la ubicación donde se encuentran todos los respaldos de los f5s
LOCAL_PATH="/localpath"  #esta es la ubicación donde se guardaran los respaldos que copiemos (se esta trabajando en crear una carpeta por ejecucion)


for REMOTE_BIGIP in `cat inventory_file.csv` #Este ciclo designa a la variable REMOTE_BIGIP la información que se encuentra almacenada en nuestro inventario de equipos
#for REMOTE_BIGIP in `cat /inventory_file.csv` #Esta linea es para ejecutar el backup con un archivo de prueba cuando agregamos nuevas ips al archivo y queremos validar que sea compatible
do
        echo -e "Respaldando F5: $REMOTE_BIGIP"    #imprimimos el texto
        name=`echo  "$REMOTE_BIGIP" | sed 's/\./\_/g'`  #creamos la variable name para asignarle el valor que tomo del archivo hostf5 y el | reemplazara los punto$
        ssh root@$REMOTE_BIGIP tmsh save /sys ucs $REMOTE_PATH/"$name"_$TIMESTAMP.ucs > /dev/null 2>&1 #nos conectamos ssh al server y ejecutamos el comando para $
        scp root@$REMOTE_BIGIP:$REMOTE_PATH/"$name"_$TIMESTAMP.ucs $LOCAL_PATH/  #realizamos la copia del archivo a nuestra carpeta local
        sleep 5
done
